spring:
  jpa:
    database-platform: com.example.internationalphonevalidator.config.SQLiteDialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:sqlite::resource:data/sample.db
    driver-class-name: org.sqlite.JDBC
countries:
  data:
    path: ./data/countries.json


